[project]
name = "myproject"
version = "0.1.0"
dependencies = [
    "torch==2.6.0+cu118",
    "torchaudio==2.6.0+cu118",
    "torchvision==0.21.0+cu118",
    "datasets==2.16.0",
    "transformers==4.50.0",
    "huggingface-hub",
    "numpy",
]
